import { Database } from "bun:sqlite";
import { mkdirSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { drizzle, type BunSQLiteDatabase } from "drizzle-orm/bun-sqlite";
import { migrate } from "drizzle-orm/bun-sqlite/migrator";
import { schema } from "./schema";

export type Db = BunSQLiteDatabase<typeof schema>;

/** App data root — ALL runtime data lives here, never in the repo (SECURITY.md).
 *  Overridable via CADENCE_HOME (used by tests to stay out of the real ~/.cadence). */
export function cadenceHome(): string {
  return process.env.CADENCE_HOME ?? join(homedir(), ".cadence");
}

export function defaultDbPath(): string {
  return join(cadenceHome(), "cadence.db");
}

/** Default migrations folder (generated by drizzle-kit), resolved relative to this file.
 *  `CADENCE_MIGRATIONS_DIR` (read in `migrateDb`) overrides it for the relocatable sidecar. */
export const migrationsFolder = join(import.meta.dir, "..", "..", "drizzle");

/** Open a Drizzle-wrapped SQLite database at `path` (":memory:" for tests). */
export function openDb(path: string = defaultDbPath()): Db {
  if (path !== ":memory:") mkdirSync(dirname(path), { recursive: true });
  const sqlite = new Database(path, { create: true });
  sqlite.exec("PRAGMA journal_mode = WAL;");
  sqlite.exec("PRAGMA foreign_keys = ON;");
  return drizzle(sqlite, { schema });
}

/** Apply all pending migrations (creates the DB + tables on first run).
 *  `CADENCE_MIGRATIONS_DIR` overrides the source-relative default so the compiled sidecar can read
 *  migrations shipped as Tauri resources (resolved at call time, not import time). */
export function migrateDb(db: Db): void {
  migrate(db, { migrationsFolder: process.env.CADENCE_MIGRATIONS_DIR ?? migrationsFolder });
}

/** Open the app DB and bring it up to date in one call. */
export function openAndMigrate(path: string = defaultDbPath()): Db {
  const db = openDb(path);
  migrateDb(db);
  return db;
}
